# Generated by Django 4.0.6 on 2022-08-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dest',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
